### ISSUE TITLE
1/12 domain_cfg

### ISSUE THREAD

**Issue by malmans2** [NOC-MSM/IMMERSE-overflows#1]
I'm currently using a eORCA12 `domain_cfg.nc`. Should switch to ORCA12 as that's the grid that will be used for the global+AGRIF run. It looks like there isn't a NEMO4 version ready, so it needs to be created using the tools.

**Comment by jdha** [comment]
Are we not using eORCA12 + AGRIF? ORCA12 is just a subset of eORCA12 so you could just _ncks_ the eORCA12 domain_cfg.nc?

**Comment by malmans2** [comment]
I think @atb299 mentioned ORCA12, but I'm gonna double check. Just cutting would make it easier (I've been lazy with the grid tools though, I should really at least take a look!).

**Comment by atb299** [comment]
As James says, it will be eORCA12 + AGRIF, and the 'e' refers to the southward extension to include the ice shelf cavities. It amounts to something like an additional 450 grid points in j. The domain used in the Met Office is here: /noc/msm/scratch/climate/atb299/IMMERSE/domaincfg_eORCA12_v1.0.nc

**Comment by malmans2** [comment]
OK, better! For some reason I thought it was gonna be ORCA. We actually already had one on ARCHER that seems more recent (v2.4). For example, I think the metoffice one has some different variables, like it's missing `bathy_meter`.

**Comment by jdha** [comment]
for ref: bathy_meter isn't a mandatory variable - this is usually derived from e3t_0 and bottom_level.
(v2.4 is the latest as far as I understand)
James
________________________________
